### ISSUE TITLE
Control_panel.context_processor issues

### ISSUE THREAD

**Issue by matnex-mix** [fedetoledo/neighborshop-api#4]
Hi, i checked out your project and i think it's cool but i'm having issues, could you please add a mini documentation and help me out here.
### Thank you
```
Environment:


Request Method: GET
Request URL: http://localhost:8000/admin/login/?next=/admin/

Django Version: 3.0.8
Python Version: 3.7.3
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'api',
 'control_panel',
 'rest_framework',
 'rest_framework.authtoken',
 'storages']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "C:\django\ecom2\env\lib\site-packages\django\utils\module_loading.py", line 20, in import_string
    return getattr(module, class_name)

The above exception (module 'control_panel.context_processors' has no attribute 'market') was the direct cause of the following exception:
  File "C:\django\ecom2\env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\django\ecom2\env\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\django\ecom2\env\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\django\ecom2\env\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\django\ecom2\env\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\django\ecom2\env\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\django\ecom2\env\lib\site-packages\django\template\base.py", line 169, in render
    with context.bind_template(self):
  File "c:\users\probook 6360b\appdata\local\programs\python\python37\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\django\ecom2\env\lib\site-packages\django\template\context.py", line 242, in bind_template
    processors = (template.engine.template_context_processors +
  File "C:\django\ecom2\env\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\django\ecom2\env\lib\site-packages\django\template\engine.py", line 85, in template_context_processors
    return tuple(import_string(path) for path in context_processors)
  File "C:\django\ecom2\env\lib\site-packages\django\template\engine.py", line 85, in <genexpr>
    return tuple(import_string(path) for path in context_processors)
  File "C:\django\ecom2\env\lib\site-packages\django\utils\module_loading.py", line 24, in import_string
    ) from err

Exception Type: ImportError at /admin/login/
Exception Value: Module "control_panel.context_processors" does not define a "market" attribute/class
```

**Comment by fedetoledo** [comment]
Hi, thank you for checking out my project, I've just fixed this. It was my bad while doing some cleaning and missed the context processor change. Currently I'm not working on documentation but I will try to make a simple readme for better understanding.
